### PR TITLE
fix for file location issue, added BSD license

### LINKED ISSUE #1: Clean up file locations
headers in include folder. yamls in launch.  source in src is good.

### PR DESCRIPTION
**Pull request by arunxdas**
resolve #1

### CODE REVIEW

**Comment by stevenwaslander** [comment]
Add a line to the Readme that says the whole package is under BSD three-clause as follows. Remove from all the other headers. For license, please refer to README

**Comment by arunxdas** [comment]
added BSD license line to README, removed license from file headers, but kept copyright info.  Ready for review @stevenwaslander @StanJBrown

**Comment by stevenwaslander** [comment]
Done! But forgot to not do the merge. Sorry, Stan, no review for you.  Next time I comment and say looks great, merge away, and don't do anything else.

**Comment by stevenwaslander** [comment]
```
Oops, went ahead and merged the pull request.  Saved you some work
Stan/Arun.  I wonder if you get this email, directly back to github
```

reply@reply.github.com
    Cheers,
    Steve

```
On 12/2/2015 2:46 PM, Arun Das wrote:



  added BSD license line to README, removed license from file
    headers, but kept copyright info. Ready for review @stevenwaslander
    @StanJBrown 
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by arunxdas** [comment]
no worries, if the merge is done, i'll delete the branch.

Thanks!
Arun

**Pull request merged**
